src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Assert\EnableAutoMapping()
 */
class Article
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="У вашей статьи должен быть заголовок")
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\DisableAutoMapping()
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;


    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @Assert\DisableAutoMapping
     */
    protected $createdAt;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     * @Assert\DisableAutoMapping
     */
    protected $updatedAt;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function isPublished(): bool
    {
        return null !== $this->getPublishedAt();
    }

    /**
     * @param ExecutionContextInterface $context
     * @param $payload
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (mb_stripos($this->getTitle(), 'собак') !== false) {
            $context->buildViolation('Про собак писать запрещено')
                ->atPath('title')
                ->addViolation();
        }
    }
}

src/Controller/Admin/ArticleController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use App\Entity\User;
use App\Form\ArticleFormType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ArticleController
 * @package App\Controller\Admin
 * @method User|null getUser()
 */
class ArticleController extends AbstractController
{
    /**
     * @IsGranted ("ROLE_ADMIN_ARTICLE")
     * @Route ("/admin/articles", name="admin_articles")
     * @param ArticleRepository $articleRepository
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(ArticleRepository $articleRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $articleRepository->latest(),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('admin/articles/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/admin/articles/create", name="admin_articles_create")
     * @param EntityManagerInterface $em
     * @return Response
     * @throws \Exception
     * @IsGranted("ROLE_ADMIN_ARTICLE")
     */
    public function create(EntityManagerInterface $em, Request $request): Response
    {
        $form = $this->createForm(ArticleFormType::class);

        if ($article = $this->handleFormRequest($form, $em, $request)) {

            $this->addFlash('flash_message', 'Статья успешно создана');

            return $this->redirectToRoute('admin_articles');
        }

        return $this->render('admin/articles/create.html.twig', [
            'articleForm' => $form->createView(),
            'showError' => $form->isSubmitted()
        ]);
    }

    /**
     * @param Article $article
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     * @Route("/admin/articles/{id}/edit", name="admin_articles_edit")
     * @IsGranted("MANAGE", subject="article")
     */
    public function edit(Article $article, EntityManagerInterface $em, Request $request): Response
    {
        $form = $this->createForm(ArticleFormType::class, $article, [
            'enable_published_at' => true,
        ]);

        if ($article = $this->handleFormRequest($form, $em, $request)) {

            $this->addFlash('flash_message', 'Статья успешно изменена');

            return $this->redirectToRoute('admin_articles_edit', ['id' => $article->getId()]);
        }

        return $this->render('admin/articles/edit.html.twig', [
            'articleForm' => $form->createView(),
            'showError' => $form->isSubmitted()
        ]);
    }

    private function handleFormRequest(FormInterface $form, EntityManagerInterface $em, Request $request)
    {
        $form->handleRequest($request); // проверяет происходила ли отправка формы, хэндлер знает каким методом форма была отправлена и какие данные должны прийти

        if ($form->isSubmitted() && $form->isValid()) {  // isSubmitted возвращает информацию была ли отправлена форма, а isValid прошла ли форма валидацию
            /** @var Article $article */
            $article = $form->getData(); // getData возвращает объект который привязан к форме, если объект не привязан возвращается ассоциативный массив

            $em->persist($article);
            $em->flush();

            return $article;
        }

        return null;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Service\SlackClient;
use Http\Client\Exception;
use Nexy\Slack\Exception\SlackApiException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     * @param ArticleRepository $repository
     * @return Response
     */
    public function homepage(ArticleRepository $repository): Response
    {
        $articles = $repository->findLatestPublished();
        return $this->render('articles/homepage.html.twig', [
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/articles/{slug}", name="app_article")
     * @param Article $article
     * @param SlackClient $slackClient
     * @return Response
     * @throws Exception
     * @throws SlackApiException
     */
    public function show(Article $article, SlackClient $slackClient)
    {
        // отправка сообщения в slack ------------
        if ($article->getSlug() == 'slack') {
            $slackClient->send('This is an amazing message!');
        }
        //------------------

        // Первый способ работы с кэшем
        /*        $item = $cache->getItem('markdown ' . md5($articleContent));

                if (!$item->isHit()) {
                    $item->set($parsedown->text($articleContent));
                    $cache->save($item);
                }
                $articleContent = $item->get();*/

        // Второй способ работы с кэшем
        /*        $articleContent = $cache->get(
                    'markdown ' . md5($articleContent),
                    function () use ($parsedown, $articleContent) {
                        return $parsedown->text($articleContent);
                    }
                );*/
        return $this->render('articles/show.html.twig', [
            'article' => $article
        ]);
    }
}

templates/articles/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Главная
{% endblock %}
{% block body %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">Главная страница</h1>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>

    <div class="container marketing">
    <div class="row">
        {% for article in articles %}
            <div class="col-lg-6">
                <h2>{{ article.title }}</h2>
                {% include 'partial/article_tags.html.twig' with {tags: article.tags} %}
                <p class="btn-info">Комментариев: {{ article.nonDeletedComments|length }}</p>
                <span>{{ article.publishedAt ? article.publishedAt|ago }}</span>
                <p>{{ article.body|u.truncate(100, '...')|cached_markdown }}</p>
                <p><a class="btn btn-secondary" href="{{ path('app_article', {slug: article.slug}) }}">Читать</a></p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/articles/show.html.twig
{% extends  'base.html.twig' %}
{% block title %}
    {{ article.title }}
{% endblock %}
{% block body %}
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">

            </div>
        </header>
    </div>

    <main class="container">
        <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 fst-italic">{{ article.title }}</h1>
                {% include 'partial/article_tags.html.twig' with {tags: article.tags} %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <article class="blog-post">
                    <p class="blog-post-meta">{{ article.publishedAt ? article.publishedAt|ago : 'Неопубликована' }}
                        <a href="#">{{ article.author.firstName }}</a></p>
                    {{ article.body|cached_markdown }}
                </article><!-- /.blog-post -->
            </div>
        </div><!-- /.row -->
        <div class="comments">
            <h3 class="title-comments">Комментарии ({{ article.nonDeletedComments|length }})</h3>
            <ul class="media-list">
                {% for comment in article.nonDeletedComments %}
                    <!-- Комментарий (уровень 1) -->
                    <li class="media">
                        <div class="media-left">
                            <img class="img-thumbnail rounded-circle" width="80" height="80" src="{{ asset('images/cat.jpg') }}" alt="">
                        </div>
                        <div class="media-body">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <div class="author">{{ comment.authorName }}</div>
                                    <div class="metadata">
                                        <span class="date">{{ comment.createdAt|ago }} {% if comment.deletedAt %} <span
                                                    style="color: red">Удален</span> {% endif %}</span>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="media-text text-justify">{{ comment.content }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <!-- Конец комментария (уровень 1) -->
                {% endfor %}
            </ul>
        </div>
    </main><!-- /.container -->
{% endblock %}